version: '3' 
services:
  api:
    build: ./docker 
    ports:
      - 8080:8080
    tty: true 
    volumes:
      - .:/go/src/music_app_api
  mysql:
        image: mysql:5.7.22
        environment:
            MYSQL_ROOT_PASSWORD: hogehoge
            MYSQL_USER: root 
            MYSQL_PASSWORD: hogehoge 
            MYSQL_DATABASE: music_app 
        container_name: mysql-container

